### ISSUE TITLE
VRRP support in ansible-role-dellos-interface

### ISSUE THREAD

**Issue by mzi77** [Dell-Networking/ansible-role-dellos-interface#1]
Hi, I need IPv4/IPv6 support, I can write it and add to project, if you are not working it.

**Comment by skg-net** [comment]
Hi Martin,

Thanks for your interest, we would be glad to accept your PR. The current
tentative plan to support VRRP in January 2017.

Thanks,
Senthil Kumar G.

**Comment by skg-net** [comment]
VRPP is supported now with new VRRP role. https://github.com/Dell-Networking/ansible-role-dellos-vrrp
